### PR TITLE
ksmbd: remove unused field in ksmbd_user struct

### PR DESCRIPTION
**Pull request by hank20010209**

### CODE REVIEW

**Comment by namjaejeon** [comment]
Are you Cheng-Han Wu ? I have checked your patch in LKML. Your patch doesn't have signed-off-by. If you are same guy who sent same patch to LKML, I will apply the patch that posted from mainline to github ksmbd.

**Comment by hank20010209** [comment]
Yes, I'm Cheng-Han Wu, I sent it to LKML. Do I need to do anything with this PR, such as closing it? I'm sorry if any inconvenience has been caused.

**Comment by namjaejeon** [comment]
Ah, no problem:) I have applied your patch to #master of this github ksmbd now. I will close this PR. Thanks for your patch!

**Comment by hank20010209** [comment]
Thank you very much.

**Pull request closed without merging**
