### PR TITLE
ksmbd: fix missing RDMA-capable flag for IPoIB device in ksmbd_rdma_capable_netdev()

### PR DESCRIPTION
**Pull request by chaserhkj**
Physical ib_device does not have an underlying net_device, thus its association with IPoIB net_device cannot be retrieved via ops.get_netdev() or ib_device_get_by_netdev(). ksmbd reads physical ib_device port GUID from the lower 16 bytes of the hardware addresses on IPoIB net_device and match its underlying ib_device using ib_find_gid()

### CODE REVIEW

**Comment by chaserhkj** [comment]
Please let me know if you'd rather make this a patch sent to the mailing list.

**Comment by namjaejeon** [comment]
> Please let me know if you'd rather make this a patch sent to the mailing list.

Yes. I want it. You need to make the patch on 6.6-rc5 kernel again. As you already know, mailing list address is  linux-cifs@vger.kernel.org . and Please CC me.

**Comment by namjaejeon** [comment]
Applied it to #master. Thanks! Please send the patch to the mailing list for mainline.

**Comment by chaserhkj** [comment]
Was a bit busy with other duties last week, just saw the thread on the mailing list. Thank you so much for submitting it for me, I can take it from here.

Closing this PR.

**Pull request closed without merging**
